### ISSUE TITLE
Getting ModuleNotFoundError on launching web Module

### ISSUE THREAD

**Issue by viaggarwal** [lucianopuccio/golem#36] opened 2017-10-21 03:48 UTC
Environment:
OS:Win7
Python: 3.6.3

Steps:
1).Installed Python 3.6.3 in Windows 7
2).Installed Golem by pip install golem-framework.
3).Created the test directory : golem-admin C:\Golem
4).Downloaded Chrome Browser Driver 2.33 and placed inside Drivers folder.
5).Started the web Module:
cd C:\Golem
python golem.py gui
6).Got the error on command prompt as attached screenshot.

However this is working fine in Python 3.4.4 version.
![golemuilauncherror](https://user-images.githubusercontent.com/23050456/31847702-7e5ce872-b5ee-11e7-8cff-a4013bd6a9c5.png)

**Comment by lucianopuccio** [comment] 2017-10-21 23:11
Hi viaggarwal, I tested this and I could not reproduce it with these conditions:
- windows 7
- python 3.6.1
- golem 0.2.2

Steps:
1. pip install golem-framework
2. golem-admin createdirectory C:\Golem
3. cd C:\Golem
4. python golem.py gui

These steps worked fine for me. The error you are getting probably means Golem is not installed where you are running the command 'python golem.py gui'. Here's what you can try:
1. See if Golem is installed by running 'pip list'
2. Try running Golem from another directory (not C:\) it could be a matter of permissions
3. Try using a virtualenv to avoid installing python packages globally,

regards

**Comment by jcnoir** [comment] 2017-11-26 08:54
I got the same issue with python 3.6.3 on Linux.
The issue looks like there is a confusion between the golem module (golem.py) and the golem package.
If I rename golem.py to golem2.py then I can launch golem correctly (but I cannot run tests because of the missing golem.py module)

**Comment by mechazilla** [comment] 2017-12-15 00:38
Same issue when installing from pip on linux. Fixed by using sudo, but had additional issues after. Problem has something to do with permissions on the site-packages when installing globally, but I didn't find the root cause. Created a virtual environment with conda and ran process again, and everything come up, but still can't create tests. Creating separate issue for this.

**Comment by lucianopuccio** [comment] 2017-12-20 03:08
as for the original issue, In version 0.4.5 I added a new command to start golem similar to 'golem-admin'. Instead of calling it as ```python golem.py <command>``` it can be called just by ```golem <command>```

Do a uninstall and re-install just in case. Also I recommend working inside a virtualenv.

Reopen if this is still happening. Thanks

**Closed** 2017-12-20 03:09 UTC
Labels: cannot reproduce

**Comment by jcnoir** [comment] 2017-12-20 20:24
It works ! Thank you for the fix.
